// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------- //
// DmxOutput //
// --------- //

#define DmxOutput_wrap_target 0
#define DmxOutput_wrap 13

#define DmxOutput_offset_start_tx 3u

static const uint16_t DmxOutput_program_instructions[] = {
            //     .wrap_target
    0xf035, //  0: set    x, 21           side 0
    0x0741, //  1: jmp    x--, 1                 [7]
    0xbd42, //  2: nop                    side 1 [5]
    0xc050, //  3: irq    clear 0 rel
    0x80a0, //  4: pull   block
    0xa047, //  5: mov    y, osr
    0x9ea0, //  6: pull   block           side 1 [6]
    0xf327, //  7: set    x, 7            side 0 [3]
    0x6001, //  8: out    pins, 1
    0x0248, //  9: jmp    x--, 8                 [2]
    0x0086, // 10: jmp    y--, 6
    0xbe42, // 11: nop                    side 1 [6]
    0xc010, // 12: irq    nowait 0 rel
    0x180d, // 13: jmp    13              side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program DmxOutput_program = {
    .instructions = DmxOutput_program_instructions,
    .length = 14,
    .origin = -1,
};

static inline pio_sm_config DmxOutput_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + DmxOutput_wrap_target, offset + DmxOutput_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

